#Cambiamos el puerto de salida
server.port=8090


spring.datasource.url=jdbc:postgresql://localhost:5433/peliculas
spring.datasource.username=postgres
spring.datasource.password=199824

#Actualiza el schema de la BD
spring.jpa.hibernate.ddl-auto=update
#Muestra los comandos SQL que esta realizndo la base desde jpa
spring.jpa.show-sql=true
#Solamente estetica para que se vea mejor en formato sql
spring.jpa.properties.hibernate.format_sql=true

langchain4j.open-ai.chat-model.api-key=demo

# Mostramos los logs
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true

#le inidcamos a spring que inicialice los datos del archivo data.sql
spring.sql.init.mode=always

# Vemos todo lo que hace langchaing4j y ai4j desde abajo con el level de debug
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG