#Cambiamos el puerto de salida
server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d9ptcgnavr4c73ac1t6g-a:5432/platzi_play_db_28to
spring.datasource.username=platzi_play_db_28to_user
spring.datasource.password=fMR5STqN2zffEMwEnkuJ1rWM9b4LHwah

#Actualiza el schema de la BD
spring.jpa.hibernate.ddl-auto=update

#le inidcamos a spring que inicialice los datos del archivo data.sql
spring.sql.init.mode=always

langchain4j.open-ai.chat-model.api-key=demo
