#Cambiamos el puerto de salida
server.port=8090


spring.datasource.url=jdbc:postgresql://localhost:5433/peliculas
spring.datasource.username=postgres
spring.datasource.password=199824

langchain4j.open-ai.chat-model.api-key=demo

# Mostramos los logs
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true

# Vemos todo lo que hace langchaing4j y ai4j desde abajo con el level de debug
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG