spring.profiles.active=dev

spring.application.name=Cine

#Cambiar el contexto de la aplicacion
server.servlet.context-path=/platzi-play/api

spring.datasource.url=jdbc:postgresql://localhost:5433/peliculas
spring.datasource.username=postgres
spring.datasource.password=199824

langchain4j.open-ai.ch at-model.model-name=gpt-4o-mini